### ISSUE TITLE
安卓

### ISSUE THREAD

**Issue by maajiko** [txperl/airAnime#11]
浏览器访问页面，页面非常卡🤔

**Comment by txperl** [comment]
你指的的卡是什么意思？资源（图片、样式）加载不出来还是交互时卡顿？

刚刚在安卓机上测试了一下，使用 WebView 的浏览器没有卡顿。

**Comment by maajiko** [comment]
> 你指的的卡是什么意思？资源（图片、样式）加载不出来还是交互时卡顿？
> 
> 刚刚在安卓机上测试了一下，使用 WebView 的浏览器没有卡顿

华为游览器，网页交互严重掉帧（指网页中）甚至卡到无法操作

**Comment by txperl** [comment]
可能是首页新番图片导致的卡顿。可目前使用的 CSS 滤镜只有 `blur`，但实际也不会消耗太多处理器资源。

可以在同一台手机上使用另一个浏览器试试？不过华为浏览器应该也是用了内建的 WebView，可能在一些细节上存在过优化。
