### ISSUE TITLE
在搜索“间谍过家家”时，搜索结果中的"#番剧官方播放地址"项内容不正确

### ISSUE THREAD

**Issue by blackusagi** [txperl/airAnime#15]
设备信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
问题描述：在搜索“间谍过家家”时，"#番剧官方播放地址"项给出的是“书家“和”谜家“两个搜索结果，怀疑和关键词匹配机制有关
截图：![问题截图](https://s3.bmp.ovh/imgs/2022/05/10/148f44400b47de00.png)

**Comment by txperl** [comment]
已在最新的 `v3` 版本中修复，感谢反馈。
