### ISSUE TITLE
您好，

### ISSUE THREAD

**Issue by NoviceLevel** [txperl/airAnime#18]
为什么我部署之后会出现搜索404问题，
![image](https://user-images.githubusercontent.com/62823553/234614900-78caa2b1-75bc-4aa9-90a4-b4f2c6d80109.png)
大佬帮看看，GitHub的一键又可以

**Comment by txperl** [comment]
应该是你没有配置 airAnime-rp 脚本，可以参考一下下面的部署方法。

https://github.com/txperl/airAnime/tree/master/api

**Comment by NoviceLevel** [comment]
嗯，部署好了但是又出新问题了
![image](https://user-images.githubusercontent.com/62823553/234856522-5472edcb-476b-45e2-b151-03e5f48c2e3e.png)

**Comment by txperl** [comment]
`AIRANIME_RP_URL` 变量地址改了吗？

**Comment by NoviceLevel** [comment]
是的，改好了，也可以正常读取

**Comment by NoviceLevel** [comment]
解决了，没想到是编辑之后格式问题，用的cPanel 在线文件编辑，麻了都

**Comment by NoviceLevel** [comment]
![image](https://user-images.githubusercontent.com/62823553/234882780-68111562-08d7-4278-90f2-5457c48b2c50.png)

**Comment by txperl** [comment]
那就好。
