### ISSUE TITLE
老师你好呀，想问一下这个网站怎么样自行添加一些新的搜索来源呀？

### ISSUE THREAD

**Issue by maotuworkroom** [txperl/airAnime#19]

**Comment by txperl** [comment]
所有数据源都在 `./vapp
/source/` 文件夹内。

其中，`./db/` 是存放本地搜索源，`./online/` 是存放在线搜索源的。

具体的搜索源代码编写，可以参考相应目录下已有的搜索源，结构都是类似的。

主要步骤就是下面这些。

- `db` 类：继承 `SourceDB`，实现 `async get(keyword, amount)` 与 `async _store(key, raw)`
- `online` 类：继承 `SourceOnline`，实现 `async format(raw)`

最后，把你实现好的搜索源类添加到 `./all.mjs` 的 `ALL_SOURCES` 常量下就好。

**Comment by maotuworkroom** [comment]
> 所有数据源都在 `./vapp
> 
> /source/` 文件夹内。
> 
> 
> 
> 其中，`./db/` 是存放本地搜索源，`./online/` 是存放在线搜索源的。
> 
> 
> 
> 具体的搜索源代码编写，可以参考相应目录下已有的搜索源，结构都是类似的。
> 
> 
> 
> 主要步骤就是下面这些。
> 
> 
> 
> - `db` 类：继承 `SourceDB`，实现 `async get(keyword, amount)` 与 `async _store(key, raw)`
> 
> - `online` 类：继承 `SourceOnline`，实现 `async format(raw)`
> 
> 
> 
> 最后，把你实现好的搜索源类添加到 `./all.mjs` 的 `ALL_SOURCES` 常量下就好。

好的感谢老师我去试试哈
