### ISSUE TITLE
以图搜番功能

### ISSUE THREAD

**Issue by Gloduck** [txperl/airAnime#2]
请问以图搜番功能我用http能上传图片但是whatanime是请求是https无法返回数据，然后https无法上传图片，请问怎么破

**Comment by txperl** [comment]
我怎么有点看不懂你的问题...

**Comment by Gloduck** [comment]
![qq 20171209222330](https://user-images.githubusercontent.com/24894908/33796475-ed1276c0-dd2f-11e7-95eb-1e0a971fb67e.png)
![qq 20171209222341](https://user-images.githubusercontent.com/24894908/33796476-ed475b4c-dd2f-11e7-88d8-5a5fbd2ac538.png)
http访问的时候无法搜索到番剧，但是在whatanime理应是搜索的到的，token配置正确

**Comment by txperl** [comment]
这是你自已搭建的吗？如果是请提供一下测试地址...如果是主站的话，我这边测试下来没问题。

**Comment by Gloduck** [comment]
www.acgkm.cn感谢

**Comment by txperl** [comment]
我这边测试下来没问题唉...

**Comment by Gloduck** [comment]
别的貌似没问题。以图搜番貌似都是找不到

**Comment by txperl** [comment]
那是因为你没有配置token，请仔细阅读README。

**Comment by Gloduck** [comment]
如果是token的话我是配置了的

**Comment by txperl** [comment]
有什么即时聊天工具的联系方式吗？你可以发邮件给我。这样子回答太累了...
