### ISSUE TITLE
关于数据加载不出的问题

### ISSUE THREAD

**Issue by Qinmei** [txperl/airAnime#3]
主页点击搜索无反应, 发现主页使用的是get方法,但是run.php使用的是POST,所以没有数据传回,改一个就好

**Comment by txperl** [comment]
已经修复了，感谢提醒！不过 airAnime v1 代码基本已经不维护了...v2 源码会在完成后放出。
哇 Qinmei 大佬！很喜欢你的 https://qinmei.video/ 哦~

**Comment by Qinmei** [comment]
受宠若惊......主题也在更新,不过暂时完善度不够,就没放出来了.

从bangumi-data获取的数据有一部分没有播放地址,这个项目可以直接搜索到D站,十分的方便啊,感谢感谢.
顺便可以考虑做个API啊

**Comment by txperl** [comment]
正在打算这样做，因为在输出前已经数组化数据了，所以很好写 API ...
你的 qinmei.video 看番也很方便啊，经常会去看的，感谢感谢！我已经把这个数据源添加到 airAnime v2 中了，希望不要介意...

**Comment by Qinmei** [comment]
没事,我用的是onedrive, 基本上没有流量的压力
