### ISSUE TITLE
whatanime.ga has moved to trace.moe

### ISSUE THREAD

**Issue by soruly** [txperl/airAnime#4]
Hello, I'm (was) the owner of whatanime.ga
A few days ago, the .ga domain was taken down by freenom T_T,
so the site has moved to https://trace.moe
if you are still actively supporting this project, please update the URL, thank you m(_ _;)m
The new API document can be found here:
https://soruly.github.io/trace.moe/

**Comment by txperl** [comment]
Sorry to hear that...
Anyway, thank you for your reminder! It has been fixed in the latest v1&v2 release.
