### ISSUE TITLE
关于爬取数据不成功的问题

### ISSUE THREAD

**Issue by sunbohit** [txperl/airAnime#5]
Hi，
    我是前端和php小白。V2版本的源码放到服务器上后，发现爬取数据全都不成功。
   用echo debug 看起来似乎是 ./function/functions.php 中的 $handle = curl_multi_init() 没有成功。想问下这里是不是有部分代码没有上传？或者我是否使用的有问题。谢谢。

**Comment by mddarmawan** [comment]
请提供屏幕截图或错误日志文件
