### ISSUE TITLE
无法搜索

### ISSUE THREAD

**Issue by Bypoishrolighta** [txperl/airAnime#9]
搜索内容后
Btrst
Results
显示loading...
PHP7.3 Debian 10 32位

https://s1.ax1x.com/2020/04/21/JY91pD.png

**Comment by txperl** [comment]
报错信息呢？

**Comment by Bypoishrolighta** [comment]
PHP Notice: Undefined index: user_id in /var/www/html/index.php on line 363
和
![image](https://user-images.githubusercontent.com/17306283/80558928-91e37680-8a0e-11ea-819e-6d3324bf0a2f.png)

**Comment by txperl** [comment]
这个 Notice 不会导致你的这个问题。PHP FPM 日志也没看出什么...

把报错打开，然后访问下 `http://your_domain/function/aonline.php` 和 `http://your_domain/function/bts.php` 看一下具体报错。

对了，如果不是最新版本，请先使用最新版试一下能否正常运行。
